<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_A</name>
   <tag></tag>
   <elementGuidId>7f9436ce-eeed-41d4-8e96-975b5b353626</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='RULE_KEY']/div/div[4]/div/div[4]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.content-item.content-field.item-1.remove-bottom-spacing.remove-right-spacing.remove-top-spacing.remove-left-spacing.flex.flex-row.image-wrapper.dataValueWrite.custom-control</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '                     A      ' or . = '                     A      ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f0b4666-db68-40b6-8099-cfe0d73d75c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content-item content-field item-1 remove-bottom-spacing remove-right-spacing remove-top-spacing remove-left-spacing flex flex-row image-wrapper dataValueWrite custom-control</value>
      <webElementGuid>12d1fce2-bc32-4877-aca6-5f45ad860522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>string_type</name>
      <type>Main</type>
      <value>field</value>
      <webElementGuid>c2f8e56f-3a5f-49ff-9905-8330cef18c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>reserve_space</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>32f615a1-43ca-4d51-834f-897aa1db947e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>                     A      </value>
      <webElementGuid>ac1019b9-b4ca-496b-8abc-012cbc93ba7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-region-one&quot;)/div[@class=&quot;screen-layout-region-content&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-simple_list  content-simple_list  portal-navigation&quot;]/div[@class=&quot;content-item content-layout item-4 flex flex-row&quot;]/div[@class=&quot;flex content layout-content-simple_list  content-simple_list  user-menu&quot;]/div[@class=&quot;content-item content-layout item-4 flex flex-row&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle pointer has-action operator-avatar&quot;]/div[@class=&quot;content-item content-field item-1 remove-bottom-spacing remove-right-spacing remove-top-spacing remove-left-spacing flex flex-row image-wrapper dataValueWrite custom-control&quot;]</value>
      <webElementGuid>be7c9df3-9ccd-44d5-b7cf-08bd088c9d72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div/div[4]/div/div[4]/div/div</value>
      <webElementGuid>1ecccd06-84b9-407d-abcc-5957cb572430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My applications'])[1]/following::div[10]</value>
      <webElementGuid>45b599ef-3e42-46e1-8c4a-ed6517f8e47a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recents'])[1]/following::div[10]</value>
      <webElementGuid>a92be5a8-b32d-43e8-bd9b-146df4b4e5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUTUSer'])[1]/preceding::div[1]</value>
      <webElementGuid>dde436c6-8d5d-4db0-b5eb-b42497fc3f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[4]/div/div</value>
      <webElementGuid>f0bec43e-fa18-4150-af0d-8ad50247b18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '                     A      ' or . = '                     A      ')]</value>
      <webElementGuid>b07964a1-3cd6-4a91-a99e-b1bddbd6b849</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
