<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Plus</name>
   <tag></tag>
   <elementGuidId>3428cdd2-0d7b-4b1c-adb7-0f5b10918d50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-$PpyNavigation1677404699179$ppyElements$l1']/a/span/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@class = 'menu-item-icon-imageclass pi pi-plus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.menu-item-icon-imageclass.pi.pi-plus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>618b189b-7eab-4efb-ae5e-d3dbcf878a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>76e39f11-0713-45c1-873f-43ad61a17f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item-icon-imageclass pi pi-plus</value>
      <webElementGuid>d7b8865a-a826-49b4-83c4-43ef63bab584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>..</value>
      <webElementGuid>46d947dc-d207-4e87-b081-42d6b4af44e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-$PpyNavigation1677404699179$ppyElements$l1&quot;)/a[@class=&quot;menu-item-anchor menu-item-expand&quot;]/span[@class=&quot;menu-item-image-wrapper&quot;]/span[@class=&quot;menu-item-icon-imageclass pi pi-plus&quot;]</value>
      <webElementGuid>604b3b11-c4f7-409b-8452-3d028073e3fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-$PpyNavigation1677404699179$ppyElements$l1']/a/span/span</value>
      <webElementGuid>02d58f82-580e-4574-b515-a3b36d7db6fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>3205e8aa-9aae-4033-bcda-8a2cf0f229b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
