<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>proceed_link</name>
   <tag></tag>
   <elementGuidId>b979c886-d4aa-46b3-b30e-f3d9e2a3fbf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sub</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='proceed-link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6575af96-efd2-4faa-a035-10811a179271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sub</value>
      <webElementGuid>d7c21d0c-0fb1-493b-af52-eeebd4439ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginButton</value>
      <webElementGuid>e6f20a32-e42b-4834-a7da-43fb86d7680b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pyActivity=Code-Security.Login</value>
      <webElementGuid>301488ad-fc63-4c07-967f-03a62a55db76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8133d38c-91e7-4b5b-8f63-f434a640a082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>removeErrorMessage();</value>
      <webElementGuid>352f4d83-9db4-414e-aa84-0828512d6b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Log in
                                        </value>
      <webElementGuid>72322943-4651-46cb-b8c4-afed2dc5cda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub&quot;)</value>
      <webElementGuid>cd2b2579-56d4-4e68-aacd-757a296b1b15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='sub']</value>
      <webElementGuid>14aaf83f-10a8-48ec-943c-5ab82e675342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='submit_row']/button</value>
      <webElementGuid>68d6cdfa-0253-49a3-88cd-ea2b477896d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[2]/following::button[1]</value>
      <webElementGuid>a38f6a1d-7245-46d8-93c2-f81bc285866e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User name'])[2]/following::button[1]</value>
      <webElementGuid>99901c22-b71d-4dfe-9ff3-36a9a821343d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password'])[1]/preceding::button[1]</value>
      <webElementGuid>7cef1177-d755-4fd6-b79b-28a9ed47c3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>517f6b12-4a64-4a0b-9b87-10fc3783da8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'sub' and @name = 'pyActivity=Code-Security.Login' and @type = 'submit' and (text() = '
                                            Log in
                                        ' or . = '
                                            Log in
                                        ')]</value>
      <webElementGuid>787e4272-b1fc-4348-a1a7-2af712ac8c89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
