<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Files  documents (2)</name>
   <tag></tag>
   <elementGuidId>32df8573-8f6b-48c2-8993-fcec9b342c3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='headerlabel8360']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headerlabel8360</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>3ed5b588-3b59-4e46-ae16-1301848b4a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-title</value>
      <webElementGuid>fdd7f4fb-3313-442c-8115-78cea9abbfbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headerlabel8360</value>
      <webElementGuid>12785d6d-ed0c-4587-9a53-1bfb22db8c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Files &amp; documents (2)</value>
      <webElementGuid>47d25f1c-cbd4-4770-bef3-30216585a8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerlabel8360&quot;)</value>
      <webElementGuid>71047114-a02d-437d-9bc3-d71c3e546a49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='headerlabel8360']</value>
      <webElementGuid>2bfdb8ea-dcd9-4a2d-aaa9-51f2584e9444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div[2]/h3</value>
      <webElementGuid>689f82a1-7581-4f26-9d0f-7f01afb184e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Be the first to post!'])[1]/following::h3[1]</value>
      <webElementGuid>c2b5b49a-0287-43bf-bc2c-50cf82a63cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='updates'])[1]/following::h3[1]</value>
      <webElementGuid>9e549d59-471e-4490-bb71-b74e38ff54f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Correspondence'])[1]/preceding::h3[1]</value>
      <webElementGuid>8641d937-6912-40d9-8acf-ed34788f7b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bertr'])[3]/preceding::h3[1]</value>
      <webElementGuid>7d8a06bd-5e40-4925-ad5c-361cacfdc80a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Files &amp; documents (2)']/parent::*</value>
      <webElementGuid>e888bc9d-954b-4802-aed9-a8ddd61b7ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h3</value>
      <webElementGuid>28eed1e4-03c5-4680-82b9-d2aa4c111b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'headerlabel8360' and (text() = 'Files &amp; documents (2)' or . = 'Files &amp; documents (2)')]</value>
      <webElementGuid>525592db-9505-4ee9-a8d9-184323414711</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
