<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Files  documents (2)_attach_Icon</name>
   <tag></tag>
   <elementGuidId>b7709293-053f-4943-a8d6-54dd5e4ab0b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='img1677416512606']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attach_Icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>db296a40-edf8-4d8d-9d88-72bcd2181120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/pyEmailThumbnail.svg</value>
      <webElementGuid>342b629c-8fc4-414a-85d9-421028806d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attach_Icon</value>
      <webElementGuid>847db35f-f544-48a5-b8c7-95fcaa34bdac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Your Voucher</value>
      <webElementGuid>461b83fc-aee4-4d0e-871b-fd1f6a3faf6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>pega.ui.HarnessActions.replaceBrokenThumbnail(this)</value>
      <webElementGuid>663669c2-b3a3-494c-a601-9f0ec6a355ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ee56cd68-a131-4841-972c-384ce01bef8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>e440b26d-ef83-4cd7-a935-f9590a986fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>faf3f498-3059-4783-9452-b52655e2d6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7088588b-9d01-4a59-9e7e-d0610ad2fada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img1677416512606&quot;)/img[@class=&quot;attach_Icon&quot;]</value>
      <webElementGuid>de11f89b-2777-4f72-862b-8276a1c8ad94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='img1677416512606']/img</value>
      <webElementGuid>4ada2831-870a-445f-9e95-fd59a18b52b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Your Voucher']</value>
      <webElementGuid>9078994a-ebc6-4123-b112-05107b6e1fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>daed2158-7461-4dca-99a0-9acbcd81b761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/pyEmailThumbnail.svg' and @alt = 'Your Voucher']</value>
      <webElementGuid>145f91bc-9063-4afe-95fa-60d3a5b61401</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
