<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bertr_attach_Icon</name>
   <tag></tag>
   <elementGuidId>32a7bdba-b69e-4b15-99cb-850244070a08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='img1677416512611']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img1677416512611 > img.attach_Icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>53b6e8bc-a0c9-4d37-9dd8-996148e08847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/pyPDFThumbnail.svg</value>
      <webElementGuid>5f0d21a6-f14f-4acf-ae81-2bc2b888e541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attach_Icon</value>
      <webElementGuid>41a4a6b0-d343-48ea-b688-c61926e9ec9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Voucher.pdf</value>
      <webElementGuid>95c76fb6-54e5-4dd9-8875-bc44c4600082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>pega.ui.HarnessActions.replaceBrokenThumbnail(this)</value>
      <webElementGuid>57278106-4872-4f5c-918f-25e5cfc808b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d36b6867-2128-4d68-b497-41deb9b7bc50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>72ca39da-ae73-4415-bdfd-d9eb10ab5797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cfb2ea38-aad6-461a-876f-5937267dc3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b5992efe-2d5b-4f7b-b804-c775f5295518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img1677416512611&quot;)/img[@class=&quot;attach_Icon&quot;]</value>
      <webElementGuid>2a026c82-2720-48a6-8ae6-2e84b19e97cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='img1677416512611']/img</value>
      <webElementGuid>d0f770c4-ce53-41e3-a485-f8a804d1ad7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Voucher.pdf']</value>
      <webElementGuid>c609bbe2-a86b-4627-828b-1b975d33119a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/div/div/div/div/div/div/a/img</value>
      <webElementGuid>e5d3c646-d928-422d-b365-f36567aa0481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/pyPDFThumbnail.svg' and @alt = 'Voucher.pdf']</value>
      <webElementGuid>bb4e6a89-6b1f-44c3-bc1a-19cc237d1a05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
