<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Resolved-Completed</name>
   <tag></tag>
   <elementGuidId>3d2c3cda-77f4-4461-9451-b96e21b18142</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='RULE_KEY']/div/div/span)[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.badge_text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>41e65d36-f472-4225-a4f8-c17236d3317e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2016083016191602341167946</value>
      <webElementGuid>12d9addc-1fde-450c-bd09-c5856c6c0d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>badge_text</value>
      <webElementGuid>eff4ca7c-6a3b-4a7d-8db1-5bf01df0944c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resolved-Completed</value>
      <webElementGuid>4f7623c8-3501-4fef-961a-6bc3ee825844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;wk chrome&quot;]/body[@class=&quot;harnessBody HID57D852CD4FBFD370FED4ACC10919A250&quot;]/div[@id=&quot;PEGA_HARNESS&quot;]/form[1]/div[@id=&quot;HARNESS_CONTENT&quot;]/div[@class=&quot;workarea-view-scroll-wrapper&quot;]/section[@class=&quot;workarea-view-content&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-inline  content-inline  main-page&quot;]/div[@class=&quot;content-item content-layout item-1 remove-all-spacing flex flex-row&quot;]/div[@class=&quot;flex content layout-content-default  content-default  summary-pane&quot;]/div[@class=&quot;content-item content-layout item-3 remove-bottom-spacing remove-right-spacing flex flex-row&quot;]/div[@class=&quot;flex content layout-content-default  content-default  scrollable-summary-pane flex-nowrap&quot;]/div[@class=&quot;content-item content-layout item-1 remove-all-spacing flex flex-row&quot;]/div[@class=&quot;flex content layout-content-default  content-default&quot;]/div[@class=&quot;content-item content-sub_section item-1 remove-top-spacing remove-left-spacing remove-right-spacing flex flex-row&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-stacked_with_labels_left  content-stacked_with_labels_left&quot;]/div[@class=&quot;content-item content-sub_section item-1 flex&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle&quot;]/div[@class=&quot;content-item content-field item-1 flex flex-row badge-bg-good centered dataValueRead&quot;]/span[@class=&quot;badge_text&quot;]</value>
      <webElementGuid>da8f9d82-e1fa-4c8d-b505-3433c86e8277</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='RULE_KEY']/div/div/span)[5]</value>
      <webElementGuid>1a554f6c-fee0-42e8-b3e6-3f28e6c6ce53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::span[1]</value>
      <webElementGuid>31c510ba-6c4e-4900-acc0-390a54eedede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priority'])[1]/following::span[1]</value>
      <webElementGuid>dffe154e-ef8f-4c88-9e5c-22ffabfce26e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created'])[1]/preceding::span[2]</value>
      <webElementGuid>5638aeb0-c93e-496d-99d1-8ecf59841775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Updated'])[1]/preceding::span[4]</value>
      <webElementGuid>d53670ba-412d-4c74-abd1-7dd912a054fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Resolved-Completed']/parent::*</value>
      <webElementGuid>4aed0415-add3-499f-ba81-e236a10906b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/div/div/div/span</value>
      <webElementGuid>72b1f4f6-14c1-4da8-bbbc-24be278efa4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Resolved-Completed' or . = 'Resolved-Completed')]</value>
      <webElementGuid>5838d158-97fa-4795-8f82-597642356420</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
