<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AN1904</name>
   <tag></tag>
   <elementGuidId>2bc7789e-19cf-4fe2-bf0d-f6e0b38e2093</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'NQ6077
				MCO
AA6340' or . = 'NQ6077
				MCO
AA6340')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='acresults_list']/ul/li/span[text()='AN1904']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ac-item.active-row</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>822eda7a-aaac-4af5-850f-d5205f2fa82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>65c4df6e-4cec-466c-a244-e7b461e689e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>31f38a6d-6888-4280-b64f-91e9a7e2f911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ac-item active-row</value>
      <webElementGuid>26ec9af6-1d20-443d-a629-f2403d9ae7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rowid</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1203dc0f-e9c7-44b2-bc2f-8a26b0acfb78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NQ6077
				MCO
AA6340</value>
      <webElementGuid>487e814e-29b2-41ed-aba8-378833f20993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acresults_list&quot;)/ul[1]/li[@class=&quot;ac-item active-row&quot;]</value>
      <webElementGuid>27585003-98d8-45ac-a67f-02eb4e6f1de2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='acresults_list']/ul/li[3]</value>
      <webElementGuid>b044ffca-c85e-49ce-8ba6-1fd224a68e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AA8099'])[1]/following::li[1]</value>
      <webElementGuid>65a9e4ed-1a95-4a60-ac80-163d0940cc7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AMS'])[1]/following::li[1]</value>
      <webElementGuid>e82d5e36-7e29-4f12-943f-be74fc0b3737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[3]</value>
      <webElementGuid>3213fbe4-97f5-45dd-abc4-ae8efa38088f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'NQ6077
				MCO
AA6340' or . = 'NQ6077
				MCO
AA6340')]</value>
      <webElementGuid>19c2649c-4752-4fd8-99e8-cfc24aeabf34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
