<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Approve</name>
   <tag></tag>
   <elementGuidId>a058defe-7d7e-4efc-92e0-37316e555e38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@data-test-id = '201410290229040300882']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='pyApproval_pyWorkPage_14']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;pyApproval_pyWorkPage_14&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc43e2fa-6d00-428c-b978-2d77652667f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201410290229040300882</value>
      <webElementGuid>33c58eca-9d41-4e76-9537-d314f6c2b2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;setValue&quot;, [[&quot;pyWorkPage.pyApprovalResult&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;Approved&quot;]]],[&quot;setUserStart&quot;,[&quot;FINISHASSIGNMENT&quot;]],[&quot;doFormSubmit&quot;,[&quot;pyActivity=FinishAssignment&quot;,&quot;:this&quot;,&quot;&quot;,&quot;:event&quot;]]]</value>
      <webElementGuid>fac848cc-0050-40e2-a82a-f80f45a89d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pyApproval_pyWorkPage_14</value>
      <webElementGuid>31ffa5cf-4474-49e5-ba32-dbcc2b8565ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Strong pzhc pzbutton</value>
      <webElementGuid>d70222d8-351e-4087-8dad-ee4ebe730f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>78890557-6cc3-4c72-a45a-6b3b786aee2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Approve this item</value>
      <webElementGuid>3888a6c6-e9b4-40ed-b10c-438ba7a98ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approve</value>
      <webElementGuid>b370549f-6a2a-445c-a9cf-965f2460bcb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pyFlowActionHTML&quot;)/span[1]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-action_buttons&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-simple_list  content-simple_list auto-width-column&quot;]/div[@class=&quot;content-item content-layout item-1 remove-all-spacing float-right set-width-auto&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;flex content layout-content-inline  content-inline set-width-auto float-right&quot;]/div[@class=&quot;content-item content-field item-3 remove-top-spacing remove-bottom-spacing remove-right-spacing flex flex-row dataValueWrite&quot;]/span[1]/button[@class=&quot;Strong pzhc pzbutton&quot;]</value>
      <webElementGuid>09de904f-a3f6-44aa-b671-28410165d12f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='pyApproval_pyWorkPage_14']</value>
      <webElementGuid>cd0eed2f-8f41-4167-a513-25a1476a523c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div[2]/div/div/div/div/div/div[3]/span/button</value>
      <webElementGuid>bd53984d-2c69-4ddf-9acd-96131aa3a32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject'])[1]/following::button[1]</value>
      <webElementGuid>db2a6116-a752-4331-973f-5a4ade8ee086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/following::button[2]</value>
      <webElementGuid>2b38378d-09c0-45a1-9b78-352ac86f0e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perform'])[1]/preceding::button[1]</value>
      <webElementGuid>8c9886b4-e5a4-411a-9665-d27aa86a3ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perform'])[2]/preceding::button[1]</value>
      <webElementGuid>6467c021-4edf-4cdf-9423-b2a544d64c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Approve']/parent::*</value>
      <webElementGuid>b7b14ecb-918a-4ca7-a169-c7501bda6a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[3]/span/button</value>
      <webElementGuid>2190457d-83ec-49a5-a94b-279053b27bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'pyApproval_pyWorkPage_14' and @type = 'button' and @title = 'Approve this item' and (text() = 'Approve' or . = 'Approve')]</value>
      <webElementGuid>6957f780-c361-4c04-bf95-f6563453b182</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
