<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create</name>
   <tag></tag>
   <elementGuidId>ca85e48e-314f-4db2-a657-c099db01e011</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@data-test-id = '20161017110917023277518']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='pyCaseActionAreaButtons_pyWorkPage_63']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;pyCaseActionAreaButtons_pyWorkPage_63&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>600efcf7-fc8a-4635-bcb6-b5848c67aedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20161017110917023277518</value>
      <webElementGuid>bc86791b-aa6e-4165-b69b-7d556303766f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;setUserStart&quot;,[&quot;FINISHASSIGNMENT&quot;]],[&quot;doFormSubmit&quot;,[&quot;pyActivity=FinishAssignment&quot;,&quot;:this&quot;,&quot;&quot;,&quot;:event&quot;]]]</value>
      <webElementGuid>06dc9557-a9b5-4498-a3c3-0b1fdc27848e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pyCaseActionAreaButtons_pyWorkPage_63</value>
      <webElementGuid>76bc0440-860f-4ce8-a2bc-35de6fb261ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Strong pzhc pzbutton</value>
      <webElementGuid>104605ec-f8dd-4715-a193-c2a553e69c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a4029c0b-3f90-4aa0-8eee-55cc55f4c09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Create this item</value>
      <webElementGuid>e8a7299f-9904-493e-912d-11fa23be3605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>c6763f73-7367-4e3b-a7e0-0e0a75084fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l1&quot;)/div[@class=&quot;screen-layout-region-content&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-inline content-inline dialog-container visible&quot;]/div[@class=&quot;content-item content-sub_section item-1 remove-all-spacing flex flex-row&quot;]/div[@class=&quot;actertiary&quot;]/div[@class=&quot;HID90536A82B5FD13A66C13225BFB6F39F7 show HID9EF5A1EC994114C475C4DD9F5F72EF06&quot;]/div[@id=&quot;PEGA_HARNESS&quot;]/fieldset[@class=&quot;mdc-fieldset&quot;]/div[@id=&quot;HARNESS_CONTENT&quot;]/footer[@class=&quot;workarea-view-footer workarea-view-footer-fixed&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-stacked  content-stacked&quot;]/div[@class=&quot;content-item content-sub_section item-1 remove-left-spacing remove-right-spacing flex flex-row padding-lr-2x&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle  action-area-buttons&quot;]/div[@class=&quot;content-item content-layout item-3 remove-right-spacing align-end flex flex-row&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle&quot;]/div[@class=&quot;content-item content-layout item-2 remove-right-spacing flex flex-row&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle&quot;]/div[@class=&quot;content-item content-field item-1 remove-right-spacing flex flex-row flow-back-button margin-l-1x dataValueRead&quot;]/span[1]/button[@class=&quot;Strong pzhc pzbutton&quot;]</value>
      <webElementGuid>30157231-7503-48a5-af67-27826d5ccf2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='pyCaseActionAreaButtons_pyWorkPage_63']</value>
      <webElementGuid>79555cd4-077e-4e80-ae3d-df2f53b25722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div/div[3]/div/div[2]/div/div/span/button</value>
      <webElementGuid>c257337c-6e98-4624-affb-10886ecfa128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/following::button[1]</value>
      <webElementGuid>c63d305c-efe3-4ad1-a54a-023115e377ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::button[2]</value>
      <webElementGuid>18bbe1b0-a03b-4cc8-81e7-b2bb15e3144e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight Management'])[1]/preceding::button[1]</value>
      <webElementGuid>2c032dfc-ce14-456e-a873-e18813936fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::button[1]</value>
      <webElementGuid>fd6507d5-f214-429a-8b9d-a338110bcf15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create']/parent::*</value>
      <webElementGuid>65aaf310-a3a9-4938-8843-fd85e52b6ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/span/button</value>
      <webElementGuid>7cb3cdc0-0ecc-4ddb-b6ef-edd1caa7f68c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'pyCaseActionAreaButtons_pyWorkPage_63' and @type = 'button' and @title = 'Create this item' and (text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>220fd80c-0fde-445b-b918-28068f8ecd57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
