<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>2f08c676-747c-4f78-8e5d-c54b63922147</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@data-test-id = '20161017110917023176385']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='pyCaseActionAreaButtons_pyWorkPage_58']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;pyCaseActionAreaButtons_pyWorkPage_58&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>017ea9a9-77d7-4e72-b55f-8a86444fe02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20161017110917023176385</value>
      <webElementGuid>d5916836-b6db-44b8-a677-4fa1562104f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;setUserStart&quot;,[&quot;FINISHASSIGNMENT&quot;]],[&quot;doFormSubmit&quot;,[&quot;pyActivity=FinishAssignment&quot;,&quot;:this&quot;,&quot;&quot;,&quot;:event&quot;]]]</value>
      <webElementGuid>8a6dd56e-cd53-4bc3-919e-49a2c6d81073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pyCaseActionAreaButtons_pyWorkPage_58</value>
      <webElementGuid>a47b3e1e-5e4b-4dcf-ae02-33362663843c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Strong pzhc pzbutton</value>
      <webElementGuid>0def83bf-021e-4999-84c6-04ce14c1c9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>accadf4c-5666-4402-9763-c96ae6f3575e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Complete this assignment</value>
      <webElementGuid>e74b89b6-cf76-4996-a518-d007489769b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>09ec27e2-6ff9-45dc-926b-6d686e822527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l1&quot;)/div[@class=&quot;screen-layout-region-content&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-inline content-inline dialog-container visible&quot;]/div[@class=&quot;content-item content-sub_section item-1 remove-all-spacing flex flex-row&quot;]/div[@class=&quot;actertiary&quot;]/div[@class=&quot;HID90536A82B5FD13A66C13225BFB6F39F7 show&quot;]/div[@id=&quot;PEGA_HARNESS&quot;]/fieldset[@class=&quot;mdc-fieldset&quot;]/div[@id=&quot;HARNESS_CONTENT&quot;]/footer[@class=&quot;workarea-view-footer workarea-view-footer-fixed&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-stacked  content-stacked&quot;]/div[@class=&quot;content-item content-sub_section item-1 remove-left-spacing remove-right-spacing flex flex-row padding-lr-2x&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle  action-area-buttons&quot;]/div[@class=&quot;content-item content-layout item-3 remove-right-spacing align-end flex flex-row&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle&quot;]/div[@class=&quot;content-item content-layout item-1 remove-right-spacing flex flex-row&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle&quot;]/div[@class=&quot;content-item content-field item-1 remove-top-spacing remove-left-spacing flex flex-row flow-back-button margin-l-1x dataValueRead&quot;]/span[1]/button[@class=&quot;Strong pzhc pzbutton&quot;]</value>
      <webElementGuid>c91d60e6-6460-43ad-87b1-0e039ef14c10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='pyCaseActionAreaButtons_pyWorkPage_58']</value>
      <webElementGuid>0c7bc5f8-ffba-4c93-a2dc-d5eaf36359b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div/div[3]/div/div/div/div/span/button</value>
      <webElementGuid>216cdf8c-5001-4a50-b4e4-8f84d411ea0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::button[1]</value>
      <webElementGuid>1e4a0947-7309-4880-86cf-3781386847cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::button[2]</value>
      <webElementGuid>aeaa8545-9fc2-4f2e-835c-a5c4c89201fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[1]/preceding::button[1]</value>
      <webElementGuid>28c7ffc4-c649-4d4b-b0a8-a2e967d0c740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight Management'])[1]/preceding::button[2]</value>
      <webElementGuid>c4becf4e-8fb1-4d2a-b147-ab9b2a50ada8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>7fd0733f-822a-46f2-9db7-a1e001a0c9b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/span/button</value>
      <webElementGuid>9b641e1a-bd29-4629-9325-eabdb6b79929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'pyCaseActionAreaButtons_pyWorkPage_58' and @type = 'button' and @title = 'Complete this assignment' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>b7df03da-8db1-4d98-966d-5dabaa8df018</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
