<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Go</name>
   <tag></tag>
   <elementGuidId>a79cff91-ed4a-4a9b-8fb1-b93b33643f4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@data-test-id = '20190208081744082718727']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='pyToDoItem_D_CaseAssignments_pa145457375380337pz.pxResults(1)_5cd7f596-1fa5-4a90-80b9-d69ef031cc50']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;pyToDoItem_D_CaseAssignments_pa145457375380337pz.pxResults(1)_5cd7f596-1fa5-4a90-80b9-d69ef031cc50&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c36fea67-0d07-4fc7-80af-f8d702bd6bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20190208081744082718727</value>
      <webElementGuid>0f020158-0124-4c8f-809d-0cef7378703a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;runScript&quot;, [&quot;pega.desktop.infinity.showHideAssignmentGadgets(\&quot;false\&quot;)&quot;],[&quot;&amp;&quot;,[&quot;OP&quot;,[&quot;$PD_CaseAssignments_pa145457375380337pz$ppxResults$l1$ppyTaskIDLabel&quot;,&quot;=&quot;,&quot;&quot;,&quot;true&quot;]]]],[&quot;setMobileTransition&quot;,[&quot;pega.SKELETON~$~pyOpenAssignmentSkeleton~$~Assign-Worklist~$~true~$~acprimary&quot;],[&quot;&amp;&quot;,[&quot;OP&quot;,[&quot;$PD_CaseAssignments_pa145457375380337pz$ppxResults$l1$ppyTaskIDLabel&quot;,&quot;=&quot;,&quot;&quot;,&quot;true&quot;]]]],[&quot;openAssignment&quot;,[&quot;#~D_CaseAssignments_pa145457375380337pz.pxResults(1).pzInsKey~#&quot;,&quot;f28a8521-60b3-4831-a37c-6b9e4a6f4007&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;#~D_CaseAssignments_pa145457375380337pz.pxResults(1).pyIsOfflineEnabled~#&quot;,{&quot;target&quot;:&quot;acprimary&quot;,&quot;pyReloadAlways&quot;:&quot;true&quot;}],[&quot;&amp;&quot;,[&quot;OP&quot;,[&quot;$PD_CaseAssignments_pa145457375380337pz$ppxResults$l1$ppyTaskIDLabel&quot;,&quot;=&quot;,&quot;&quot;,&quot;true&quot;]]]],[&quot;setMobileTransition&quot;,[&quot;pega.mobile.transitions.NONE&quot;],[&quot;|&quot;,[&quot;OP&quot;,[&quot;$PD_CaseAssignments_pa145457375380337pz$ppxResults$l1$ppyTaskIDLabel&quot;,&quot;!=&quot;,&quot;&quot;,&quot;false&quot;]]]],[&quot;openAssignment&quot;,[&quot;#~D_CaseAssignments_pa145457375380337pz.pxResults(1).pzInsKey~#&quot;,&quot;3194dd47-6320-4d34-9aee-65b4a53bbb52&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;#~D_CaseAssignments_pa145457375380337pz.pxResults(1).pyIsOfflineEnabled~#&quot;,{&quot;target&quot;:&quot;primary&quot;,&quot;pyReloadAlways&quot;:&quot;false&quot;}],[&quot;|&quot;,[&quot;OP&quot;,[&quot;$PD_CaseAssignments_pa145457375380337pz$ppxResults$l1$ppyTaskIDLabel&quot;,&quot;!=&quot;,&quot;&quot;,&quot;false&quot;]]]]]</value>
      <webElementGuid>1ed04ab5-fc28-42cf-836a-1edefa08eca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pyToDoItem_D_CaseAssignments_pa145457375380337pz.pxResults(1)_5cd7f596-1fa5-4a90-80b9-d69ef031cc50</value>
      <webElementGuid>360fff2b-d6ad-4415-a1d4-eb2796cf23ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Strong pzhc pzbutton</value>
      <webElementGuid>fe3e0c69-ec8a-422d-bbd4-08100143227e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>302e8540-9df6-4582-b35c-0c50f33a2399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>baee709a-e816-41c2-91c7-8dcb1d0f53bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>f64860ab-3da0-4392-8cf0-159258892a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9cf343a3-a295-4bf5-9edd-87b19f5fa491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a72f4a56-887f-4d02-85be-8c83c76bd90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>c95dc27f-8d9a-4e30-8bb7-25d6970f6a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HARNESS_CONTENT&quot;)/div[@class=&quot;workarea-view-scroll-wrapper&quot;]/section[@class=&quot;workarea-view-content&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-inline  content-inline  main-page&quot;]/div[@class=&quot;content-item content-layout item-2 remove-all-spacing flex flex-row&quot;]/div[@class=&quot;flex content layout-content-inline  content-inline  main-content-wrapper position-relative flex-nowrap&quot;]/div[@class=&quot;content-item content-layout item-1 remove-all-spacing flex flex-row&quot;]/div[@class=&quot;flex content layout-content-simple_list  content-simple_list  sticker&quot;]/div[@class=&quot;content-item content-sub_section item-4 remove-all-spacing flex flex-row min-height-0&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@id=&quot;EXPAND-OUTERFRAME&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;rdlWrapperDiv&quot;]/div[@class=&quot;content    flex  layout-content-stacked content-stacked list-border-b-standard progressive-onclick&quot;]/div[@class=&quot;content-item content-sub_section item-1 flex flex-row&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle auto-width-column flex-grow-1-item-2 flex-nowrap flex-none-item-1 flex-none-item-3&quot;]/div[@class=&quot;content-item content-layout item-3 remove-top-spacing remove-left-spacing remove-right-spacing align-end set-width-auto flex flex-row&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle set-width-auto&quot;]/div[@class=&quot;content-item content-field item-1 remove-top-spacing remove-bottom-spacing remove-right-spacing flex flex-row right-aligned dataValueRead&quot;]/span[1]/button[@class=&quot;Strong pzhc pzbutton&quot;]</value>
      <webElementGuid>8540419a-2acc-430a-b0e6-f52161caae6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='pyToDoItem_D_CaseAssignments_pa145457375380337pz.pxResults(1)_5cd7f596-1fa5-4a90-80b9-d69ef031cc50']</value>
      <webElementGuid>8db86218-d561-46a8-89ea-b572f54da673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='RULE_KEY']/div/div[3]/div/div/span/button)[3]</value>
      <webElementGuid>e8a2cf6f-ed5d-403b-b47d-bed16818c986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refund Approval (Refund Approval)'])[1]/following::button[1]</value>
      <webElementGuid>9038c578-89d4-4d39-97a4-3a1647c435d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Platinum'])[1]/following::button[1]</value>
      <webElementGuid>6e2f8f23-b4f6-4da7-815d-aa2afe028e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[2]/preceding::button[1]</value>
      <webElementGuid>6d9eb089-3661-41be-8b7d-345294775ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[3]/preceding::button[1]</value>
      <webElementGuid>c8a5df56-4c3a-47a8-b7e5-2d4593300e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Go']/parent::*</value>
      <webElementGuid>b8826796-f9f0-423b-bc84-473a3efe59c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]/div/div/span/button</value>
      <webElementGuid>422c5457-a9ae-4eb4-b648-916097717e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'pyToDoItem_D_CaseAssignments_pa145457375380337pz.pxResults(1)_5cd7f596-1fa5-4a90-80b9-d69ef031cc50' and @type = 'button' and (text() = 'Go' or . = 'Go')]</value>
      <webElementGuid>83643013-bc69-40cc-9385-f11a1336b091</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
