<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Notes</name>
   <tag></tag>
   <elementGuidId>c5afcc44-2ffa-4604-8107-dfc1cb223f45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='2ccf1030']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#2ccf1030</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@data-test-id = '201505150624190386338']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8abe35a2-3896-4cbb-976f-75d4f39e5d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201505150624190386338</value>
      <webElementGuid>8612b486-5a7d-4d73-8c64-8e55e39575e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2ccf1030</value>
      <webElementGuid>92dd5e60-560e-4526-969e-479c4886359c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TANORM textAreaStyle</value>
      <webElementGuid>ac6566a7-db9c-424f-83a8-872c9bf0095d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$ppyNote</value>
      <webElementGuid>30287a4d-ff9e-45c3-a9c9-1cdb9ca13a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-exp</name>
      <type>Main</type>
      <value>Enter to Collapse</value>
      <webElementGuid>d0e1ed7d-0dc8-4768-b5aa-3f59e96c0d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-col</name>
      <type>Main</type>
      <value>Enter to Expand</value>
      <webElementGuid>93f6905f-e419-422e-8693-3cf2cde4da83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d9f046dd-9a84-4211-999d-50ba5943a35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextArea&quot;,{&quot;height&quot;:&quot;auto&quot;}]</value>
      <webElementGuid>5104b681-6344-4828-93e6-27dc758ee392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PpyWorkPage$ppyNoteError</value>
      <webElementGuid>9c2d89c4-cf89-416a-82fa-0cc44beb26f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>32e73532-1cfa-4250-b30a-554c9649fbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2ccf1030&quot;)</value>
      <webElementGuid>482145a5-1205-4298-bb46-85306f474882</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='2ccf1030']</value>
      <webElementGuid>b6292de3-a461-4cca-b242-90a4e35058cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='CTRL_TA']/textarea</value>
      <webElementGuid>1be9ce8b-d63a-4fd6-b108-c87bfd8a4096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>aea3ccce-6f9b-40b1-b0a4-9db6d6ffae49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = '2ccf1030' and @name = '$PpyWorkPage$ppyNote']</value>
      <webElementGuid>d9dc652e-f8af-4bd9-9cac-171b4212f7ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
