<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PNR - TestID</name>
   <tag></tag>
   <elementGuidId>faece5ad-1bc1-4b38-a3fd-91751666f722</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-test-id = '202212270943270446807']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2e1c8e5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2e1c8e5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2844eb60-25db-46a1-8bb4-1b25c78fb022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6432a275-709e-4a20-86b3-61f3ccf89642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>009f34fe-0114-4f62-9ca2-765543f0d2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6fbb2d0d-389c-4178-8452-24cef13dea6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>781d5f65-f7b4-4f41-8905-8ce145b849b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>04ca4740-2551-4986-82b6-c48644fb21b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e4992df6-5ec4-4fd5-b6cc-439a72e89375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change-lazy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c5435e40-447c-439c-bb29-4071727cab2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkQvQUNURVJUSUFSWV8wfWMyYWYxMTY4NGEyNTU1OGE5ZjE0ZjZhODUxMmE3OGY2NzgwMDRmM2I1YWYxN2M2ZWY4OTgxYTc2YWVlMGMxOWM2MzFlMDM2NDg1NDFlN2JhMWExMzY2MmYyZjc4N2U4MjBkZTdjNTI1ZWY2ODk0MGQwNmQ5M2ZjYzAyMjRiZDVhODVjNjFmZjBlMDE0MDBmMGE5NzVmOWJlODk0ZWViMDU1ZGNmZmZlODZlOWFlNzg0YTQzOThkMmE0NWJmMGNlZDlkMjVlODNmNjc4NjVmNWE3ZWY1NWQ0NDUzNTQzY2Ez*&quot;,{},{}],&quot;pyWorkPage.SelectBooking&quot;]]]</value>
      <webElementGuid>2a6e4eae-b9a2-44c3-89a3-77701c9946be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>202212270943270446807</value>
      <webElementGuid>896df418-14c5-4222-a8c9-585265450483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;AutoCompleteAG&quot;]</value>
      <webElementGuid>f1e18637-5128-4404-a598-18e68663ffc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dadf757f-c3d1-4362-83f7-d995d0ff405b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2e1c8e5</value>
      <webElementGuid>abf7d703-ff7c-4ea3-8aa5-a8846183d2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autocomplete_input ac_</value>
      <webElementGuid>fd7f8719-1aaa-4dcc-a061-ebc81a0b4095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-config</name>
      <type>Main</type>
      <value>[&quot;datapage&quot;,[&quot;D_BookingList&quot;],[[&quot;.Pnr&quot;,&quot;true&quot;,&quot;true&quot;,&quot;true&quot;,&quot;Associated property&quot;],[&quot;.DepartureStation&quot;,&quot;true&quot;,&quot;true&quot;],[&quot;.Number&quot;,&quot;true&quot;,&quot;true&quot;],[&quot;.pyGUID&quot;,&quot;false&quot;,&quot;false&quot;,&quot;true&quot;,&quot;pyWorkPage.SelectBooking.pyGUID&quot;]],&quot;true&quot;,&quot;false&quot;,&quot;true&quot;,[],&quot;false&quot;]</value>
      <webElementGuid>283b7546-6c9e-4044-a621-44f36aa7ea7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-displayfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>20c371d3-18d2-41e9-9417-ba62cc95d0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attributes</name>
      <type>Main</type>
      <value>[&quot;EXPANDEDSubSectionCollectBookingID_SelectBooking_search826c397a_011d_49d3_b0ed_a39eb3d84a25_Pnr&quot;,0,170,{},&quot;pyWorkPage.SelectBooking&quot;,0,false]</value>
      <webElementGuid>9a1b26ee-8243-4e61-b353-28635a18cbdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pSelectBooking$pPnr</value>
      <webElementGuid>399232f0-7a7e-4c70-9fc6-9fd2017b8648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PpyWorkPage$pSelectBooking$pPnrError </value>
      <webElementGuid>f2188838-890f-4fa4-9aad-023395512edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-skip-ac</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>7df81525-05ef-49b5-bf33-156ac04e61b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f1e45147-3155-40ed-a1e4-b9f154135265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2e1c8e5&quot;)</value>
      <webElementGuid>87424901-6c05-43e4-8179-74015b4357fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2e1c8e5']</value>
      <webElementGuid>8a288424-a815-4f39-8667-35a3abd41f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='RULE_KEY']/div/div/div/div/input)[16]</value>
      <webElementGuid>a3d4daa0-096f-4410-9d5b-f8b9c3c433db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/input</value>
      <webElementGuid>1015f23f-461a-4ce0-8382-4c0068be2b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b2e1c8e5' and @name = '$PpyWorkPage$pSelectBooking$pPnr']</value>
      <webElementGuid>60ce808c-afe6-493d-b6c8-9ef4805939e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
