<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PNR</name>
   <tag></tag>
   <elementGuidId>c636601c-af19-4e4c-87c8-0aa905e65dd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2e1c8e5']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-test-id = '202212270943270446807']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2e1c8e5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4434ef84-9357-46fb-9738-cd6d7bb83d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f3e81ac5-6419-43ed-8e60-8a6f1679885f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f8703bbd-5dbc-41e6-aada-8d25c393b1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5985fb50-f57a-4c5b-81bb-58d9a973203d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>26456761-934e-413b-9880-4e244b48589c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>b5e86769-4ca2-4ec6-b8da-f79de252816b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c4f68cff-e916-46d9-8cb1-41dfb802f04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change-lazy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c9da6a3a-060c-4f5d-bd93-dbfda12f358b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkQvQUNURVJUSUFSWV8wfWMyYWYxMTY4NGEyNTU1OGE5ZjE0ZjZhODUxMmE3OGY2NzgwMDRmM2I1YWYxN2M2ZWY4OTgxYTc2YWVlMGMxOWM2MzFlMDM2NDg1NDFlN2JhMWExMzY2MmYyZjc4N2U4MjBkZTdjNTI1ZWY2ODk0MGQwNmQ5M2ZjYzAyMjRiZDVhODVjNjFmZjBlMDE0MDBmMGE5NzVmOWJlODk0ZWViMDU1ZGNmZmZlODZlOWFlNzg0YTQzOThkMmE0NWJmMGNlZDlkMjVlODNmNjc4NjVmNWE3ZWY1NWQ0NDUzNTQzY2Ez*&quot;,{},{}],&quot;pyWorkPage.SelectBooking&quot;]]]</value>
      <webElementGuid>590af910-36ff-4fc3-bdfd-a7aed7a67dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>202212270943270446807</value>
      <webElementGuid>d07df45f-d7f6-48ce-9fc1-521a1cc8cbf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;AutoCompleteAG&quot;]</value>
      <webElementGuid>a944dbfa-d490-4853-8c67-1e16caf0b449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>68a03252-2622-4509-9ac7-a38b0ac06881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2e1c8e5</value>
      <webElementGuid>c488e95c-d6a1-4afa-af4c-9a27aef8c070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autocomplete_input ac_</value>
      <webElementGuid>d31cd00e-01cc-4a8d-81e7-0174d1cf044e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-config</name>
      <type>Main</type>
      <value>[&quot;datapage&quot;,[&quot;D_BookingList&quot;],[[&quot;.Pnr&quot;,&quot;true&quot;,&quot;true&quot;,&quot;true&quot;,&quot;Associated property&quot;],[&quot;.DepartureStation&quot;,&quot;true&quot;,&quot;true&quot;],[&quot;.Number&quot;,&quot;true&quot;,&quot;true&quot;],[&quot;.pyGUID&quot;,&quot;false&quot;,&quot;false&quot;,&quot;true&quot;,&quot;pyWorkPage.SelectBooking.pyGUID&quot;]],&quot;true&quot;,&quot;false&quot;,&quot;true&quot;,[],&quot;false&quot;]</value>
      <webElementGuid>ab456873-acd0-4730-bcf0-a050c1d9350c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-displayfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f2ba4e3f-f955-4848-8931-101b51fe1cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attributes</name>
      <type>Main</type>
      <value>[&quot;EXPANDEDSubSectionCollectBookingID_SelectBooking_search826c397a_011d_49d3_b0ed_a39eb3d84a25_Pnr&quot;,0,170,{},&quot;pyWorkPage.SelectBooking&quot;,0,false]</value>
      <webElementGuid>722a497c-e109-45a1-baeb-8f8e1c8c649d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pSelectBooking$pPnr</value>
      <webElementGuid>219b5273-5430-4df2-a213-b67f2fa39306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PpyWorkPage$pSelectBooking$pPnrError </value>
      <webElementGuid>c795f240-77a9-417c-87a4-9f0da0e6ae87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-skip-ac</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>e5b81d39-3a25-4e4e-bc18-284d838704b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fd8ed653-d772-4b7b-9521-1cadb86f63a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2e1c8e5&quot;)</value>
      <webElementGuid>7cae5746-ffa5-489f-a718-56b56a1d7111</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2e1c8e5']</value>
      <webElementGuid>5aacb2b7-a8eb-425a-b7d5-26e25ef2e445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='RULE_KEY']/div/div/div/div/input)[16]</value>
      <webElementGuid>3ddf3b7b-d318-413a-8b3a-32592298bb94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/input</value>
      <webElementGuid>4fb27ceb-2346-4e00-bdd1-4ea884a8669b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b2e1c8e5' and @name = '$PpyWorkPage$pSelectBooking$pPnr']</value>
      <webElementGuid>7acc9c04-5aa9-4006-9dcd-450b749dd9d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
