<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Refund Percentage</name>
   <tag></tag>
   <elementGuidId>aa1c75e3-0914-466c-a01c-2e5ad1b8f317</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='7532912e']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@data-test-id = '202212271040460421586']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#7532912e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9548d3cf-fb54-4d08-80da-8dd6c7645ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>202212271040460421586</value>
      <webElementGuid>48c9391e-a446-444c-aa1e-9ec83642f2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
      <webElementGuid>715afbb2-82a5-4009-bd5b-b54e0ebf01f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>6a1b629d-e24d-4fd5-afd1-9104363bc605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7532912e</value>
      <webElementGuid>4f844ff6-4777-43f9-a470-1c03cb7babf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>3a121cdb-8437-43ec-996f-03c7778a8bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leftJustifyStyle</value>
      <webElementGuid>0bc16fbf-bf6a-4af3-995a-2c33f5f3340a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pRefundPercentage</value>
      <webElementGuid>d9dfc85d-0094-4fca-8997-bb6ac4c60426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>integer,calculateexpression</value>
      <webElementGuid>2d83fcd1-3d46-49c8-a3e9-6b389ba46aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PpyWorkPage$pRefundPercentageError </value>
      <webElementGuid>a50ac5bf-9bcb-4602-9381-1a02aeb18995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3caa58a9-7a1b-49d4-9628-567cee72dbe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>92794d90-0900-49dd-b160-4775fae8aa09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7532912e&quot;)</value>
      <webElementGuid>3d6bf633-00f6-46dd-ad2d-842458ba5963</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='7532912e']</value>
      <webElementGuid>f2a2b253-972c-4699-9cdf-65b128555ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div/div/div/span/input</value>
      <webElementGuid>9f757653-5e1f-4a54-bf61-9b19f982b499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>7c940007-e95b-4ddc-958f-5b2d2409c6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = '7532912e' and @name = '$PpyWorkPage$pRefundPercentage']</value>
      <webElementGuid>630ee60c-b7ac-4e2f-af46-68f7012e9306</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
